# Generated by Django 2.2.3 on 2019-07-31 15:45

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190730_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=markdownx.models.MarkdownxField(help_text='Markdown形式に対応しています'),
        ),
    ]
